pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:icaiuma/momrisr.git
          - cd momrisr.git
          - git push --mirror git@github.com:icai-uma/MOMRISR.git